sudo: required
services:
  - docker

script:
  - export REPO=frosner/docker-rstudio
  - docker build -t $REPO .

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export COMMIT=${TRAVIS_COMMIT::8}
  - export NICE_BRANCH_NAME=$(echo $TRAVIS_BRANCH | sed -e 's/\//_/g')
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo "$NICE_BRANCH_NAME" ; fi`
  - docker tag $REPO $REPO:$COMMIT
  - docker tag $REPO $REPO:$TAG
  - docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO